gem 'omniauth-facebook'
gem 'omniauth-github'
gem 'omniauth-google-oauth2'
gem 'omniauth-twitter'
gem 'stripe'
gem 'stripe_event'
gem 'braintree'

group :test do
  gem 'stripe-ruby-mock', github: 'rebelidealist/stripe-ruby-mock'
end